services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformFormBuilderReportBundle\UI\Tab\ReportTab:
        tags:
            - { name: ezplatform.tab, group: location-view }

